# Generated by Django 5.1.6 on 2025-03-25 08:20

import app_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='random_number',
            field=models.IntegerField(default=app_blog.models.random_number, verbose_name='Рандомне число'),
        ),
    ]
